document.getElementById("upd-tipo-despacho").addEventListener("click",()=>{
    document.getElementById("tipo-despacho2").disabled=false;
})
document.getElementById("upd-transportista").addEventListener("click",()=>{
    document.getElementById("transportista2").disabled=false;
})
document.getElementById("upd-atencion").addEventListener("click",()=>{
    document.getElementById("atencion2").disabled=false;
})
document.getElementById("upd-direccion").addEventListener("click",()=>{
    document.getElementById("direccion2").disabled=false;
})
document.getElementById("upd-vendedor-asignado").addEventListener("click",()=>{
    document.getElementById("vendedor-asignado2").disabled=false;
})